# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0002_auto_20170802_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tasklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasklist', to='tasklist.Tasklist'),
        ),
    ]
